title: GNU Octave
email: octave-maintainers@gnu.org
description: >- # this means to ignore newlines until "baseurl:"
  GNU Octave is a programming language for scientific computing.

# For GNU Savannah <https://www.gnu.org/software/octave>
#url: "https://www.gnu.org"  # the base hostname & protocol for your site
#baseurl: "/software/octave"

# For GitHub pages
url: "https://gnu-octave.github.io"

discourse_url: "https://octave.discourse.group/"
wiki_url: "https://wiki.octave.org"
faq_url: "https://wiki.octave.org/faq"
docs_url: "https://octave.org/doc/latest/"
bugs_url: "https://bugs.octave.org/"
sourceforge_url: "https://octave.sourceforge.io"
packages_url: "https://gnu-octave.github.io/packages/"
maintainers_email: "octave-maintainers@gnu.org"
help_email: "help-octave@gnu.org"
irc_channel: "#octave"
irc_network: "irc.freenode.net"
timezone: "UTC0"

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Empty 'include' list overrides the default setting `include: [".htaccess"]`.
# See <https://github.com/jekyll/jekyll/issues/3958>.
include: []

exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
  - README.md
  - .htaccess  # Needed for GNU Savannah
