title: GNU Octave
email: octave-maintainers@gnu.org
description: >- # this means to ignore newlines until "baseurl:"
  GNU Octave is a programming language for scientific computing.
#baseurl: "/software/octave"  # only needed for publication at gnu.org
url: "https://www.gnu.org"    # the base hostname & protocol for your site
discourse_url: "https://octave.discourse.group/"
wiki_url: "https://wiki.octave.org"
faq_url: "https://wiki.octave.org/faq"
docs_url: "https://www.gnu.org/software/octave/doc/latest"
bugs_url: "https://savannah.gnu.org/bugs/?group=octave"
sourceforge_url: "https://octave.sourceforge.io"
maintainers_email: "octave-maintainers@gnu.org"
help_email: "help-octave@gnu.org"
irc_channel: "#octave"
irc_network: "irc.freenode.net"
timezone: "UTC0"

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
